import type { Metadata } from "next";
import { Architects_Daughter } from 'next/font/google';
import "./globals.css";

const archDaughter = Architects_Daughter({ 
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archDaughter.className} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
